name: Build FNF Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install Project Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install hxp
          haxelib run hxp setup

      - name: Run Lime Build for Android
        run: |
          haxelib run lime build android -DFEATURE_CHART_EDITOR

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ThatOneDevEngine-APK
          path: export/**/android/bin/**/*.apk
          
